# Generated by Django 5.2.4 on 2025-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_api', '0003_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
