# Generated by Django 5.2.4 on 2025-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_api', '0006_alter_doctorprofile_user_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(default='M|F', max_length=6),
        ),
    ]
