# Generated by Django 5.2.4 on 2025-07-28 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_api', '0007_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(),
        ),
    ]
