name: Prettier Format Check

on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci || npm install
          npx prettier --version

      - name: Run Prettier (Check mode)
        run: npx prettier . --check

      - name: Run Prettier (Format and check diff)
        run: |
          npx prettier . --write
          git diff --exit-code || (echo "Prettier formatting needed" && exit 1)
